### ISSUE TITLE
Generate enigma-go from OpenAPI v3 specification

### ISSUE THREAD

**Issue by wennmo** [qlik-oss/enigma-go#73]
Currently enigma-go is generated from the JSON RPC specification. If we want enigma-go to include the enums from the API we need to generate from the OpenAPI specification instead.

The specification can be fetched on `http://localhost:9076/openapi/rpc` from a running container.

**Comment by glooms** [comment]
The way to generate enums is not obvious, since what we want is not really enumeration but compile-time argument restriction.

This could be implemented using structs which implement the interface [TextMarshaler](https://golang.org/pkg/encoding/#TextMarshaler). To enforce the usage of predefined values we could have publicly exposed variables of private struct types.

The downsides of such a solution is that the syntax for using "enums" would become something like:
`enigma.CharacterEncodingType.Utf8`
depending on implementation of course and that it would increase the complexity of the code.

**Comment by glooms** [comment]
You could also implement a solution that only provides argument restriction by for example creating a
`type CharacterEncodingType string` which implements the `MarshalText` method. This method would then simply return the type's string value but only if it matches a set of accepted values.

This would be backwards compatible, although not sure if it would work since the marshaler might just use the literal value without running the MarshalText method. (In that case we need a struct instead but that would break the backwards compatibility.)
